package org.testautomation.projectenums;

public enum PropertiesEnum {

    ACCOUNTINGCENTER_URL,
    GTZPARTNER_URL,
    RATINGCENTER_URL,
    GTZSHIP_URL,
    AGENTDISPUTEBOARD_URL,
    GTZDEMAND_URL,
    URL,
    ACCOUNTING_CENTER_USER_NAME,
    ACCOUNTING_CENTER_PASSWORD,
    GTZSHIP_USER_NAME,
    GTZSHIP_PASSWORD,
    RATING_CENTER_USER_NAME,
    RATING_CENTER_PASSWORD

}
